# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.gupta.buttons.linkinpark.com:

networks:
  shipping:

services:

  peer0.gupta.buttons.linkinpark.com:
    container_name: peer0.gupta.buttons.linkinpark.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.gupta.buttons.linkinpark.com
      - CORE_PEER_ADDRESS=peer0.gupta.buttons.linkinpark.com:7451
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7451
      - CORE_PEER_CHAINCODEADDRESS=peer0.gupta.buttons.linkinpark.com:7452
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7452
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gupta.buttons.linkinpark.com:7451
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gupta.buttons.linkinpark.com:7451
      - CORE_PEER_LOCALMSPID=GuptaButtonsMSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/atri/workspace_hlf/shipping-network/organizations/gupta.buttons/organization/peerOrganizations/gupta.buttons.linkinpark.com/peers/peer0.gupta.buttons.linkinpark.com/msp:/etc/hyperledger/fabric/msp
        - /home/atri/workspace_hlf/shipping-network/organizations/gupta.buttons/organization/peerOrganizations/gupta.buttons.linkinpark.com/peers/peer0.gupta.buttons.linkinpark.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gupta.buttons.linkinpark.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7451:7451
    networks:
      - shipping

  OrgToolscli:
    container_name: OrgToolscli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=OrgToolscli
      - CORE_PEER_ADDRESS=peer0.gupta.buttons.linkinpark.com:7451
      - CORE_PEER_LOCALMSPID=GuptaButtonsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/gupta.buttons/organization/peerOrganizations/gupta.buttons.linkinpark.com/peers/peer0.gupta.buttons.linkinpark.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/gupta.buttons/organization/peerOrganizations/gupta.buttons.linkinpark.com/peers/peer0.gupta.buttons.linkinpark.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/gupta.buttons/organization/peerOrganizations/gupta.buttons.linkinpark.com/peers/peer0.gupta.buttons.linkinpark.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organization/peerOrganizations/gupta.buttons.linkinpark.com/users/Admin@gupta.buttons.linkinpark.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - /home/atri/workspace_hlf/shipping-network/chaincode/:/opt/gopath/src/github.com/chaincode
        - /home/atri/workspace_hlf/shipping-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    depends_on:
      - peer0.gupta.buttons.linkinpark.com
    networks:
      - shipping
