################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &GuptaButtons
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: GuptaButtonsMSP

        # ID to load the MSP definition as
        ID: GuptaButtonsMSP

        MSPDir: /home/atri/workspace_hlf/shipping-network/organizations/gupta.buttons/organization/peerOrganizations/gupta.buttons.linkinpark.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('GuptaButtonsMSP.admin', 'GuptaButtonsMSP.peer', 'GuptaButtonsMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('GuptaButtonsMSP.admin', 'GuptaButtonsMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('GuptaButtonsMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('GuptaButtonsMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.gupta.buttons.linkinpark.com
              Port: 7451